[package]
name = "sibsecsh"
version = "0.1.0"
authors = ["Zhang Maiyun <myzhang1029@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipaddress = "0.1.0"
toml = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.0"
re = "0.1.0"
log = "0.4.0"
simplelog = "0.9.0"
lettre = "0.9.0"
rpassword = "5.0.0"
subprocess = "0.2.0"
home = "0.5.0"