[package]
name = "sibsecsh"
version = "0.3.2"
authors = ["Zhang Maiyun <myzhang1029@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exec = "0.3"
home = "0.5"
ipaddress = "0.1"
lettre = "0.9"
lettre_email = "0.9"
log = "0.4"
native-tls = "0.2"
oath = "0.10"
rand = "0.8"
regex = "1"
serde = { version = "1", features = ["derive"] }
simplelog = "0.11"
subprocess = "0.2"
toml = "0.5"
users = "0.11"
