[package]
name = "sibsecsh"
version = "0.3.2"
authors = ["Zhang Maiyun <myzhang1029@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cidr = "0.2"
exec = "0.3"
home = "0.5"
lettre = "0.9"
lettre_email = "0.9"
log = "0.4"
native-tls = "0.2"
oath = { version = "0.10", git = "https://github.com/myzhang1029/rust-oath" }
rand = "0.8"
regex = "1"
serde = { version = "1", features = ["derive"] }
simplelog = "0.12"
subprocess = "0.2"
toml = { version = "0.5", default-features = false }
users = "0.11"
